### ISSUE TITLE
504: Gateway Timeout when trying to add .gitignore behind proxy

### ISSUE THREAD

**Issue by LaurentChardin** [CodeZombieCH/vscode-gitignore#1]
The 'Add gitignore' command does not seem to work when behing a proxy : it generates a `504: Gateway Timeout` error message.

The following environment variables http_proxy and https_proxy are set. 
And VScode is respecting them since i could download the extension.

**Comment by CodeZombieCH** [comment]
Thank you for reporting this issue. I will take a closer look at this.

**Comment by CodeZombieCH** [comment]
I just asked the Visual Studio Code team what would be the recommended way to support proxy from an extension other than writing everything from scratch or copy&paste code from Visual Studio Code code base. As soon as I receive feedback I will post an update here and start with the implementation.

**Comment by ibigpapa** [comment]
I too am hitting this issue

**Comment by ibigpapa** [comment]
I think the proper way would be to pull the proxy information from the configurations.  If i understand the documentation correctly the workspace.getconfig command actually pulls a merged Global config with settings in workspace config overwriting the globals.

Then i guess since code is available on github you might be able to extract the http request they use when it uses the proxy.  I believe it's in the extensions code section.

**Comment by CodeZombieCH** [comment]
@ibigpapa: Thanks for your research. I came up with almost the same solution when I was looking for a solution. As the implementation is already part of Visual Studio Code, I asked them if they could expose the proxy settings through an API (see https://github.com/Microsoft/vscode/issues/12588). So far I have no information if the node package has been published. 

As I have some time this weekend, I plan to implement proxy support this weekend by copy&paste the vscode implementation and publish it as version 0.5.0.

**Comment by CodeZombieCH** [comment]
I just completed the proxy support implementation and tested it with a proxy set by Visual Studio Code settings.

@ibigpapa @LaurentChardin I would very much appreciate if you find some time installing the alpha version at the end of this comment and verify if this versions works with your proxy setup. Thanks a lot.

Alpha version: https://drive.google.com/open?id=0B6-NC49ru2VGMTdSYjZ2dV96STg

**Comment by jeedev0815** [comment]
I have tested the 0.50-alpha version and it works with my proxy settings!
I had previously also the problems as described by @ibigpapa .
Thanks!

**Comment by ibigpapa** [comment]
Tested on my system without a proxy and works just fine.  Turned on the proxy and tested again and it still works 👍

**Comment by CodeZombieCH** [comment]
Thank you @jeedev0815 and @ibigpapa for the feedback. I will release the new version within the next days.
