### ISSUE TITLE
.net core

### ISSUE THREAD

**Issue by lasharela** [CodeZombieCH/vscode-gitignore#11]
Is any .gitignore file available for a .net core?

**Comment by CodeZombieCH** [comment]
This extension is not providing you with `.gitignore` files by itself but pulling them from the https://github.com/github/gitignore repository. As such I suggest you take a look at this repository and ask for a .NET Core template or contribute a template by yourself.

You might as-well take a look at the [VisualStudioCode.gitignore](https://github.com/github/gitignore/blob/master/Global/VisualStudioCode.gitignore) and [VisualStudio.gitignore](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore) files.
