### ISSUE TITLE
Error ``<!DOCTYPE html>``

### ISSUE THREAD

**Issue by vilinski** [CodeZombieCH/vscode-gitignore#2]
Command "Add gitignore" does nothing and emits an error with this text `<!DOCTYPE html>`

Environment:
Windows 7 with firewall
VSC 1.4.0
CodeZombie.gitignore 0.2.0
michelemelluse.gitignore 1.0.1

**Comment by CodeZombieCH** [comment]
Are you using a proxy?

**Comment by CodeZombieCH** [comment]
I assume this was caused by a proxy.
Resolved by #1 in Version 0.5.0

**Comment by vilinski** [comment]
yes it was proxy, thank you for fix
