### ISSUE TITLE
"Certificate has expired"

### ISSUE THREAD

**Issue by kramrm** [CodeZombieCH/vscode-gitignore#20]
When I try to pull a template, I get a "certificate has expired" warning message.

**Comment by CodeZombieCH** [comment]
If this is still an issue, could you please provide more details. Are you using a proxy?

**Comment by kramrm** [comment]
Given this issue is 1.5 years old, I had uninstalled the plugin.  I just reinstalled, and it looks like the certificate has been fixed.
