### ISSUE TITLE
Aliases not resolved

### ISSUE THREAD

**Issue by n2o** [CodeZombieCH/vscode-gitignore#21]
First of all: Thanks for this project!

There is a problem when the github/gitignore repository references another .gitignore file. Currently, the other referenced file is not being resolved.

For example:

<kbd>CMD+Shift+p</kbd> > Add gitignore > Clojure

creates a .gitignore-file containing the line [`Leiningen.gitignore`](https://github.com/github/gitignore/blob/master/Clojure.gitignore) (Leiningen is a build tool for Clojure projects. But resolving the contents of that Leiningen.gitignore would be better. The contents of Leiningen.gitignore are the interesting lines.

It would be much better, if content from that Leiningen.gitignore is pasted into the newly created .gitignore.

Thanks :-)

**Comment by CodeZombieCH** [comment]
These "aliases" turned out to be symlinks. 

This can be resolved by:
- using the gitignore REST API provided by Github (see https://docs.github.com/en/rest/reference/gitignore)
- building a service that clones the repository locally, so the symlinks act as regular files

**Comment by CodeZombieCH** [comment]
Fixed with version https://github.com/CodeZombieCH/vscode-gitignore/releases/tag/v0.8.0
