### ISSUE TITLE
publish on open-vsx

### ISSUE THREAD

**Issue by JHerseth** [CodeZombieCH/vscode-gitignore#22]
Could you publish this on open-vsx.org so it can be installed directly in vscodium ?
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by CodeZombieCH** [comment]
Thanks for letting me know about project. Let me have a closer look...

**Comment by CodeZombieCH** [comment]
I just release the gitignore extension to the Open VSX Registry:
https://open-vsx.org/extension/codezombiech/gitignore

Hope that helps :rocket:

**Comment by JHerseth** [comment]
Thank you! 👍
