### ISSUE TITLE
Open VSX Listing: Signing the Publisher Agreement

### ISSUE THREAD

**Issue by spoenemann** [CodeZombieCH/vscode-gitignore#23]
Thank you for being part of the Open VSX community by adding your extensions to the Open VSX Registry. Please note that the service was recently transferred to the Eclipse Foundation and urgent action on your part is needed so we can continue to list your extensions. To ensure uninterrupted service, please sign the [Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf) **on or before January 8, 2021**. If not signed by that date, your extensions will be delisted and will no longer appear on the site nor be available via the API. If you sign at a later date, your extensions will then be re-activated. The signing process is [explained in the Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) (steps 1 and 2).

Please also note that all extensions MUST have a license in order to be listed.

More details are in these recent blog posts:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry

Today, there’s growing momentum around open source tools and technologies that support Visual Studio (VS) Code extensions. Leading global organizations are adopting these tools and technologies. This momentum has spurred demand for a marketplace without restrictions and limitations. Thanks for joining us on this journey as we continue to build the Open VSX community. We look forward to continued innovation from you in 2021!

**Comment by brianking** [comment]
@CodeZombieCH Just a reminder for you in case you missed this. Our deadline was extended but the new one is approaching fast, this Friday January 29.

**Comment by jnnkB** [comment]
It would be really cool to have vscode-gitignore in there again.

**Comment by CodeZombieCH** [comment]
@brianking Sorry for the late reply, I will take care of this within the next days.

**Comment by CodeZombieCH** [comment]
I signed the Eclipse Publisher Agreement today. The extension should now be available again:
https://open-vsx.org/extension/codezombiech/gitignore

**Comment by jnnkB** [comment]
Unfortunately there still seems to be an problem. See the blue message below.
![screenshot](https://user-images.githubusercontent.com/29376715/120070894-031bb000-c08d-11eb-87f9-f5ff73026c9e.png)

**Comment by brianking** [comment]
The blue message is site-wide and does not apply to the extension. It is just a notice.

@CodeZombieCH The orange notice below it will not go away until you, as the namespace owner, publish a newer version of the extension.

**Comment by CodeZombieCH** [comment]
@brianking Your right, I forgot to publish the latest version of the extension. Will do this tonight...

**Comment by CodeZombieCH** [comment]
Turns out I cannot release the same version again. I'm working on the next release already. Once its ready, I will make sure to publish to both registries so this should be resolved.
