### ISSUE TITLE
search within subfolders

### ISSUE THREAD

**Issue by russinow** [CodeZombieCH/vscode-gitignore#3]
some .gitignore files in https://github.com/github/gitignore are in Global subfolder and ext. can't find them. So, if I searching for JetBrains.gitignore file, I can't add it by this ext. Can you make search within subfolders?

**Comment by CodeZombieCH** [comment]
This feature is now implemented with v0.3.0 of the extension. The update has been published to the extension marketplace and will show up as an update soon. Thanks for requesting this feature.

**Comment by russinow** [comment]
thanks :)
