### ISSUE TITLE
.gitignore Already Exists

### ISSUE THREAD

**Issue by Sidneys1** [CodeZombieCH/vscode-gitignore#4]
When the `.gitignore` already exists, ask to append to it instead.

**Comment by CodeZombieCH** [comment]
Thanks for your feature request. I had the same idea a week ago and already started working on this. I will publish this feature within the next days.

**Comment by CodeZombieCH** [comment]
This features is now implemented and will ship with version 0.4.0. I would appreciate any feedback from you on how you like the implementation.

**Comment by FrancisVila** [comment]
I have version 1.46.1, and this is what I get when I select "add to .gitignore" : 
![image](https://user-images.githubusercontent.com/23334974/86326361-e343f800-bc41-11ea-8872-34ad4a375afb.png)
