### ISSUE TITLE
Support for .gitattributes

### ISSUE THREAD

**Issue by hashhar** [CodeZombieCH/vscode-gitignore#7]
Will you be willing to accept a PR that adds similar support for .gitattribute files?

**Comment by CodeZombieCH** [comment]
Why not :-)
What exactly do you have in mind?

**Comment by hashhar** [comment]
I think the same mechanism that you use to pull .gitignore files can be applied to .gitattributes files at https://github.com/alexkaratarakis/gitattributes.

This would add a new command to the command palette. One command for ignore, one command for attributes.

**Comment by CodeZombieCH** [comment]
I like your idea. I'm just not sure if it follows the "Write programs that do one thing and do it well" philosophy. I think that both  `.gitignore`and `.gitattributes` files helps you properly configuring your git project. On the other side, this extension is named _gitignore_.
I will think about this over the weekend and let you know...

**Comment by hashhar** [comment]
In that case, I think I'll simply create a new extension I think? Thanks. Have a merry Christmas. 🎅

**Comment by hashhar** [comment]
I have written an [extension](https://marketplace.visualstudio.com/items?itemName=hashhar.gitattributes).

**Comment by CodeZombieCH** [comment]
@hashhar nice work :thumbsup:
